### ISSUE TITLE
aixinwu网站整体升级更换了，请求更新

### ISSUE THREAD

**Issue by SadPull** [kody-black/auto-aixinwu-sjtu#1]
已经白嫖很久了，突然失效了感觉不习惯呜呜呜

**Comment by kody-black** [comment]
更新了，快给我个star 🐶

**Comment by SadPull** [comment]
已经star了 感谢感谢捏~

**Comment by SadPull** [comment]
![image](https://github.com/user-attachments/assets/c8e901ba-52c5-425c-aad2-e2e71ec2b8fd)
一波操作猛如虎，闪来闪去的一下就签到好了，太感谢了呜呜呜呜
